blank_issues_enabled: true
contact_links:
  - name: Chat on Nostr
    url: https://njump.to/npub19802see0gnk3vjlus0dnmfdagusqrtmsxpl5yfmkwn9uvnfnqylqduhr0x
    about: Prefer a conversation? Reach out on Nostr.
